### ISSUE TITLE
Why can't Passenger find Rails assets?

### ISSUE THREAD

**Issue by mayordwells** [pacuna/dckerize#8]
I have opened an issue on the passenger package and asked a question on stackoverflow.
Trying to get my app to load the assets from public folder after dockerizing my app with your gem. 

Please take a look:

https://github.com/phusion/passenger-docker/issues/246

https://stackoverflow.com/questions/54728978/using-the-passenger-docker-image-how-can-i-configure-docker-to-get-assets-from

For some reason, it's not trying to get the assets from public folder, but from the root. Why?

<img width="1280" alt="screen shot 2019-02-17 at 2 42 55 am" src="https://user-images.githubusercontent.com/1370340/52910068-36164d00-32a3-11e9-83da-03d238ac009c.png">

**Comment by pacuna** [comment]
Hi @mayordwells sorry for the late response.  I see you already solved the problem in the other issue so I'm closing this one.
Thanks.
